version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "wmware-data-visualisation"
s3_prefix = "sam-app"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

